### ISSUE TITLE
Hot swapping videos

### ISSUE THREAD

**Issue by boshan** [kyle8998/Vynchronize#24]
What would be really cool and unique would be the ability to switch videos without losing the place of the previous video and be able to freely switch between videos.

**Comment by kyle8998** [comment]
Interesting idea. This is currently the case when swapping between different players.

One possible way of doing this in the same player would to simply store all video data when swapping or just have two video player instances.

This will be an experimental feature for now.

**Comment by kyle8998** [comment]
@boshan 

I'm happy to say I finally implemented a previous video function! Users can now, at the click of a button, go back to the last video they played!

Thanks for the idea! 👍 

5cd362283ed4912b4dd4fa13fdcda7b85e99a555
