### ISSUE TITLE
Web Application Complete Crash

### ISSUE THREAD

**Issue by kyle8998** [kyle8998/Vynchronize#43]
For some unknown reason the heroku app completely crashes and has to be redeployed. This occurred when two sockets were connected to a room, then went inactive for a bit of time. 

I'm currently not aware of the exact issue at the moment.

**Comment by kyle8998** [comment]
Cannot reproduce. This may just be a one time issue with heroku.

**Comment by ParityError** [comment]
I've noticed after testing the heroku app it's crashed two times in two days. 

![vynchronize_error](https://user-images.githubusercontent.com/36368048/41577279-cd2ab79e-7340-11e8-8d00-3d19fba4a864.png)

Seems like it's more than a one-time issue.

**Comment by kyle8998** [comment]
Yep, I guess now having a bunch of people on it triggered something. I am trying to figure out what the issue is.

**Comment by ParityError** [comment]
One thing I noticed is that it only happened when one of the connections was a mobile client. No idea though if that was just by coincidence or if it's actually relevant.

**Comment by kyle8998** [comment]
It seems as it occurs when the app goes to sleep/crashes when people are connected to rooms. When the server comes back up the sockets that are already existing are attempting to access previous room information that no longer exist. Will look into this more soon.

**Comment by kyle8998** [comment]
Finally Resolved 4495453fa11a382c361ad7e8aedc3ab0e9bb78d4
