### ISSUE TITLE
Chat Room Design Overhaul

### ISSUE THREAD

**Issue by kyle8998** [kyle8998/Vynchronize#7]
Redesign the chat room front end. Right now it looks clunky, and does not fit well with the video player.

**Comment by boshan** [comment]
Where do we leave suggestions?

**Comment by kyle8998** [comment]
> Where do we leave suggestions?

Go to the issues tab, and create an issue! Please create an issue for suggestions, bugs, or enhancements! I will personally go through every issue! :)
