### ISSUE TITLE
add support for mp4 and webm, html5 player ?

### ISSUE THREAD

**Issue by Smallinger** [kyle8998/Vynchronize#88]
For me it would be cool to have the possibility to watch my own mp4's and webm's.
like http://example.com/videofile.mp4
I think this should be possible with the Html5 player.

**Comment by kyle8998** [comment]
I'll look into it thanks!

**Comment by DavidCarl** [comment]
How have this gone? Been looking into a service that could do this, and actually thought about implementing it myself, just dont wanna program it all if most of it already is done.

**Comment by kyle8998** [comment]
@DavidCarl 
> How have this gone? Been looking into a service that could do this, and actually thought about implementing it myself, just dont wanna program it all if most of it already is done.

I've looked into it only a bit so far. I need to figure out a good way to upload and retrieve videos over web sockets/database.

**Comment by DavidCarl** [comment]
My idea was not to host it yourself (like upload a file) but rather just
provide a link to where it's located if that makes sense:)

**Comment by kyle8998** [comment]
> My idea was not to host it yourself (like upload a file) but rather just
> provide a link to where it's located if that makes sense:)

Do you mean providing a direct link to say a .mp4 file? That should be possible, and definitely a lot easier. The use case would be small though because there are not many websites that just provide a mp4 link. If you were to upload your own video, where would you upload it so you can access the mp4 link?

**Comment by DavidCarl** [comment]
Personally I got a 6TB server running plex and some other stuff ;) That is where I would do it from (again in my case).

**Comment by kyle8998** [comment]
@DavidCarl 

HTML5 Player from direct url support added. It is not perfect right now, it's actually probably pretty buggy.

ad4ab3c9f2c907ef9e32954b80faf43609844632
